kafka:
  producer:
    brokers:
      - "kafka:29092"
    client_id: dummy-error-producer
    topic: scrape.errors.audit
  consumer:
    brokers:
      - "kafka:29092"
    group_id: ${oc.env:HOSTNAME,dummy-error-consumer}
    topics:
      - "scrape.errors"
    auto_offset_reset: latest

streaming:
  observability:
    log:
      enabled: true
      config:
        name: dummy_loom_streaming
        environment: ${oc.env:ENVIRONMENT,dev}
        renderer: ${oc.env:LOG_RENDERER,console}
        colors: ${oc.decode:${oc.env:LOG_COLORS,true}}
        level: ${oc.env:LOG_LEVEL,DEBUG}
    otel:
      enabled: true
      export_logs: true
      config:
        service_name: ${oc.env:OTEL_SERVICE_NAME,dummy-error-pod}
        tracer_name: dummy-loom-streaming
        endpoint: ${oc.env:OTEL_EXPORTER_OTLP_ENDPOINT,http://otel-lgtm:4318/v1/traces}
        protocol: ${oc.env:OTEL_EXPORTER_OTLP_PROTOCOL,http/protobuf}
    prometheus:
      enabled: ${oc.decode:${oc.env:PROMETHEUS_ENABLED,false}}
      config:
        path: ${oc.env:PROMETHEUS_PATH,/metrics}
