kafka:
  producer:
    brokers:
      - "redpanda:9092"
    client_id: dummy-sync-producer
    topic: scrape.audit
  producers:
    scrape.requests:
      brokers:
        - "redpanda:9092"
      client_id: dummy-sync-producer-requests
      topic: scrape.requests
    scrape.sync.errors:
      brokers:
        - "kafka:29092"
      client_id: dummy-sync-errors-producer
      topic: scrape.errors
  consumer:
    brokers:
      - "kafka:29092"
    group_id: ${oc.env:HOSTNAME,dummy-sync-consumer}
    topics:
      - "scrape.responses"
    auto_offset_reset: latest

streaming:
  smoke:
    api_base: https://dummyjson.com
    expand_product_catalog:
      api_base: https://dummyjson.com
    expand_categories:
      api_base: https://dummyjson.com
    expand_category_products:
      api_base: https://dummyjson.com
  observability:
    log: true
    otel: true
    otel_config:
      service_name: ${oc.env:OTEL_SERVICE_NAME,dummy-sync-pod}
      tracer_name: dummy-loom-streaming
      endpoint: ${oc.env:OTEL_EXPORTER_OTLP_ENDPOINT,http://otel-lgtm:4318/v1/traces}
      protocol: ${oc.env:OTEL_EXPORTER_OTLP_PROTOCOL,http/protobuf}

logging:
  level: info
